feat: Synchronous Client: Remove mut from methods
bytebeamio/rumqtt pull request #646
Opened 2023-06-21 17:43 UTC by BKDaugherty

I realized that the synchronous client might not actually need to take `&mut` self instead of `&self` here. My team has been wrapping this in an Arc<Mutex<>> 🙃 (Yes I know it's also cheaply Cloned!), and I was hoping that moving this to `&self` would help our use case.

## Type of change

New feature (non-breaking change which adds functionality)

## Checklist:

- [X] Formatted with `cargo fmt`
- [ ] Make an entry to `CHANGELOG.md` if its relevant of user of the library. If its not relevant mention why.

2023-11-09 04:35 UTC, swanandx requested changes
please sync up the with latest main branch to resolve the merge conflicts, rest LGTM! Thank you for the PR :smile:

2023-11-09 04:35 UTC, swanandx commented on rumqttc/CHANGELOG.md
> +- Synchronous client methods take `&self` instead of `&mut self` (#646)
move this to unreleased changes section

2023-11-09 18:54 UTC, BKDaugherty commented
Thanks for the review @swanandx! Rebased on main, and updated the changelog! Would love another look!

2023-11-10 01:45 UTC, swanandx approved these changes

2023-11-10 06:28 UTC, merged