fix: validate subprotocol mqtt
bytebeamio/rumqtt pull request #724
Opened 2023-10-05 10:44 UTC by Vilayat-Ali

Added validation to check for response headers for websocket subprotocol for "mqtt" and returns a new error `WebsocketSubprotocol` variant if absent.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] Formatted with `cargo fmt`
- [ ] Make an entry to `CHANGELOG.md` if it's relevant to the users of the library. If it's not relevant mention why.

2023-10-05 10:53 UTC, de-sh requested changes

2023-10-05 10:53 UTC, de-sh commented on mosquitto.conf
Remove this file

2023-10-05 10:53 UTC, de-sh commented on rumqttc/examples/websocket.rs
Undo these changes

2023-10-05 10:53 UTC, de-sh commented on rumqttc/src/eventloop.rs
> +                .ok_or(Err(ConnectionError::WebsocketSubprotocol));
```suggestion
                .ok_or(Err(ConnectionError::WebsocketSubprotocol))?;
```

2023-10-05 10:53 UTC, de-sh commented on rumqttc/src/eventloop.rs
> +                .ok_or(Err(ConnectionError::WebsocketSubprotocol));
```suggestion
                .ok_or(Err(ConnectionError::WebsocketSubprotocol))?;
```

2023-10-05 16:21 UTC, Vilayat-Ali commented on rumqttc/src/eventloop.rs
> +                .ok_or(Err(ConnectionError::WebsocketSubprotocol));
done

2023-10-05 16:21 UTC, Vilayat-Ali commented on rumqttc/src/eventloop.rs
> +                .ok_or(Err(ConnectionError::WebsocketSubprotocol));
done

2023-10-06 11:22 UTC, de-sh commented
@swanandx any plans on fixing clippy suggestions?

2023-10-06 11:46 UTC, swanandx commented
> any plans on fixing clippy suggestions?
>
me must haha, should we open separate PR for it ( would need to sync up this branch after merging it )? or just fix it in this one?

> Test against a broker that supports websocket
>
will do!

2023-10-06 12:26 UTC, swanandx reviewed
Tested with rumqttd when it sends "mqtt" and when doesn't ( in which case it closed the connection as expected ). Though this PR isn't covering all the cases ( explained in review comments ), please address them!

Otherwise, great work with PR :100:

2023-10-06 12:26 UTC, swanandx commented on rumqttc/src/websockets.rs
> +    SubprotocolMqtt(String),
can we rename this variant to something that will indicate that we can't find "mqtt" in subprotocols list?

2023-10-06 12:26 UTC, swanandx commented on rumqttc/src/websockets.rs
> +    }
as per specs [ref](https://http.dev/ws#sec-websocket-protocol):
> This header can appear multiple times within the request, or instead, multiple subprotocols can be listed in a comma-delimited format
> 

here, we aren't covering cases where multiple protocols are listed. e.g.
`Sec-WebSocket-Protocol: something-idk, mqtt`

suggestions: we can split the header at `,` and then check if `mqtt` exists!

2023-10-06 12:26 UTC, swanandx commented on rumqttc/src/websockets.rs
> +        .map_err(|_| ValidationError::SubprotocolHeaderMissing)?;
if we can't convert it to string ( i.e. it isn't utf8 ) shouldn't mean it was missing right? we can probably use the other variant which shows it wasn't "mqtt"?

2023-10-07 07:55 UTC, de-sh commented
@Vilayat-Ali please go through the changes suggested by @swanandx and the last two commits made to fix the PR along the repo code style. Please note the reorg of code and the naming conventions used.

2023-10-07 07:55 UTC, merged