refactor(rumqttc): Replace Vec with FixedBitSet for QoS 2 packet trac…
bytebeamio/rumqtt pull request #869
Opened 2024-05-21 15:13 UTC by hippalus

…king.(#868)

## Type of change

- Refactor (code improvements and optimizations)
- Replaced `Vec<Option<u16>>` with `FixedBitSet` for `outgoing_rel` and `incoming_pub`.
- Updated methods to accommodate the new data structure, including `clean`, `handle_incoming_pubrec`, `handle_incoming_pubrel`, and others.
- Updated unit tests to ensure correct functionality with the new data structure.
refactor(mqtt_state): Replace Vec with FixedBitSet for QoS 2 packet tracking (#868)

Refactored the `MqttState` struct to use `FixedBitSet` instead of `Vec<Option<u16>>` for the `outgoing_rel` and `incoming_pub` fields. This change optimizes memory usage and improves performance for tracking packet identifiers in QoS 2 operations.
 
## Checklist:

- [X] Formatted with `cargo fmt`
- [ ] Make an entry to `CHANGELOG.md` if it's relevant to the users of the library. If it's not relevant mention why.

2024-05-21 15:16 UTC, hippalus commented
Before
![Screenshot 2024-05-06 at 15 14 22](https://github.com/bytebeamio/rumqtt/assets/17534654/32e4054c-1dd7-4be7-8428-9e46b43a571e)

After
![Screenshot 2024-05-21 at 17 07 01](https://github.com/bytebeamio/rumqtt/assets/17534654/c488f3f7-d3d9-4a5a-8860-fb87da06bb10)

2024-05-22 09:34 UTC, de-sh requested changes
Thanks for the PR, these are some really good changes, would appreciate if you could undo the unrelated ones and apply similar updates to `v5/state.rs`. Please update `CHANGELOG.md` as well.

2024-05-22 09:34 UTC, de-sh commented on rumqttc/src/state.rs
> +use crate::mqttbytes::*;
This change seems to be unrelated to the core of this PR

2024-05-22 09:34 UTC, de-sh commented on rumqttc/src/state.rs
> +    Deserialization(#[from] Error),
same as above

2024-05-22 09:36 UTC, de-sh commented on rumqttc/src/state.rs
> +    Deserialization(#[from] Error),
We have placed things this way to make it clear where that particular error is trickling down from.

2024-05-22 14:12 UTC, de-sh approved these changes
LGTM 
Great first PR @hippalus! 🎊 

edit: sorry, forgot to mention that we need an update to the `rumqttc/CHANGELOG.md` file

2024-05-22 14:19 UTC, merged

2024-05-22 14:27 UTC, Arend-Jan commented
now that is what I call an improvement. Thanks @hippalus 🙏

2024-05-27 02:37 UTC, xiaocq2001 commented
Reduce the pkid to fixed bit seems work, but it assumes the pkids from host is within 1 to max inflight. It seems in MQTT spec there is no rule to limit packet identifiers in this way.
I think there could be issue to handle if a broker sending randomized or very large pkids, or scattered pkids.

2024-05-27 13:05 UTC, de-sh commented
> I think there could be issue to handle if a broker sending randomized or very large pkids, or scattered pkids, e.g., the bit to pkid value issue, the pkid actual ordering issue.

Is this with regards to v4/5?

2024-05-27 13:39 UTC, swanandx commented
> Is this with regards to v4/5?
>
both. I think what @xiaocq2001 wants to say is let's say we have max inflight set to 100, but nothing is stopping broker from using 200 as pkid right? 

so now when we get incoming pub with pkid 200, we will try to insert it and crash! please correct me if wrong.

btw, if this is the issue, then i think it was still there before this PR.

2024-05-28 01:22 UTC, xiaocq2001 commented
There is another while re-sending the PUBREL packets, as described in MQTTv5 spec, "The Client MUST send PUBREC packets in the order in which the corresponding PUBLISH packets were received (QoS 2 messages) [MQTT-4.6.0-3]", this means if a connection is resumed the previous order of outgoing PUBREL must be restored, but `FixedBitSet` of `outgoing_ref` does not support ordering other than continuous and increasing pkid.

E.g., if broker sending packets with pkids 4,1,2,3 the expected `outgoing_ref` should be 4,1,2,3, but currently if it's disconnected and reconnected before the `outgoing_ref` sent, the resumed packet ordering is 1,2,3,4 which is not expected.

Another consideration is, for outgoing PUBLISH and PUBREL packets, they may need more information for status notification (https://github.com/bytebeamio/rumqtt/issues/805), in such cases we must use larger structs instead of just one bit for each packet.