Enable native tls TlsConnectBuilder support.
bytebeamio/rumqtt pull request #870
Opened 2024-05-22 08:07 UTC by xiaocq2001

## Type of change

New feature (non-breaking change which adds functionality)
* `Transport::tls_with_config` now accepts `native_tls::TlsConnectorBuilder` instance as input, to customize options

## Checklist:

- [ ] Formatted with `cargo fmt`
- [ ] Make an entry to `CHANGELOG.md` if it's relevant to the users of the library. If it's not relevant mention why.

2024-05-22 08:09 UTC, xiaocq2001 commented on rumqttc/src/lib.rs
> +#[derive(Clone)]
derive of Debug is removed because TlsConnectorBuilder has no Debug trait, not sure if there is better idea for it.

2024-05-24 07:42 UTC, xiaocq2001 commented
Considering that the `Native` could be used to simplify native configuration to use OS settings, and there may be compatible issue, I added new `NativeBuild` to accept builder as input.

2024-05-30 17:01 UTC, de-sh approved these changes
Hopefully no one depends on `TlsConfiguration` being `Debug`, `Transport` ain't so LGTM

2024-05-31 10:21 UTC, de-sh commented on rumqttc/examples/tls_native.rs
> +    let cert = native_tls::Certificate::from_pem(pem).unwrap();
```suggestion
    let cert = native_tls::Certificate::from_pem(&pem).unwrap();
```

2024-05-31 12:00 UTC, de-sh commented
Since we don't do much with the `Builder` under the hood, why not just ask the user to build it first?

2024-06-03 01:44 UTC, xiaocq2001 commented
> Since we don't do much with the `Builder` under the hood, why not just ask the user to build it first?

I just keep align with the implement for `rustls` where `ClientConfig` is passed to build connection.

2024-06-03 07:55 UTC, xiaocq2001 commented on rumqttc/src/lib.rs
> +#[derive(Clone)]
Close the discuss. Use TlsConnector which has debug trait.

2024-06-06 01:47 UTC, xiaocq2001 commented
Added wss (WebSocket Secure) support.
tls-native works fine connecting to mosquitto public broker.

Facing issue when using rustls, it always fail with "failed to lookup address information: Name or service not known", I guess some specific certification should be used?

2024-06-10 15:56 UTC, de-sh approved these changes

2024-06-17 07:41 UTC, xiaocq2001 commented
It's approved and tests are green, is there any more thing I need to do to let it merged?

BTW, is there any timeline for next rumqttc release and crate update?

2024-06-17 08:02 UTC, swanandx commented
> It's approved and tests are green, is there any more thing I need to do to let it merged?
> 
hey, thanks for your patience and reminder :) actually we got caught up with other work and so this was missed.

> BTW, is there any timeline for next rumqttc release and crate update?
>
due to same reason of not having much bandwidth, can't commit to any specific date rn, but should be quite soon.

2024-06-17 12:46 UTC, de-sh commented on rumqttc/src/v5/eventloop.rs
> +        #[cfg(all(any(feature = "use-rustls", feature = "use-native-tls"), feature = "websocket"))]
```suggestion
        #[cfg(all(feature = "use-rustls", feature = "websocket"))]
```

2024-06-17 12:47 UTC, de-sh commented on rumqttc/src/v5/eventloop.rs
> +            #[cfg(all(feature = "use-rustls", not(feature = "use-native-tls")))]
```suggestion
```

2024-06-17 12:47 UTC, de-sh commented on rumqttc/src/eventloop.rs
> +        #[cfg(all(any(feature = "use-rustls", feature = "use-native-tls"), feature = "websocket"))]
```suggestion
        #[cfg(all(feature = "use-rustls", feature = "websocket"))]
```

2024-06-17 12:47 UTC, de-sh commented on rumqttc/src/eventloop.rs
> +            #[cfg(all(feature = "use-rustls", not(feature = "use-native-tls")))]
```suggestion
```

2024-06-18 01:05 UTC, xiaocq2001 commented on rumqttc/examples/wss.rs
Done.

2024-06-18 01:06 UTC, xiaocq2001 commented
> Please move changes regarding wss from this PR to another

OK. I'll create another PR for websocket changes after this one is merged.

2024-06-18 07:41 UTC, swanandx approved these changes

2024-06-18 08:01 UTC, de-sh requested changes

2024-06-18 08:01 UTC, de-sh commented on rumqttc/src/lib.rs
> +))]
```suggestion
#[cfg(any(feature = "use-rustls", feature = "websocket"))]
```

2024-06-18 08:01 UTC, de-sh commented on rumqttc/src/lib.rs
> +    #[cfg_attr(docsrs, doc(cfg(all(any(feature = "use-rustls", feature = "use-native-tls"), feature = "websocket"))))]
```suggestion
    #[cfg(all(feature = "use-rustls", feature = "websocket"))]
    #[cfg_attr(docsrs, doc(cfg(all(feature = "use-rustls", feature = "websocket"))))]
```

2024-06-18 08:01 UTC, de-sh commented on rumqttc/src/lib.rs
> +    #[cfg_attr(docsrs, doc(cfg(all(any(feature = "use-rustls", feature = "use-native-tls"), feature = "websocket"))))]
```suggestion
    #[cfg(all(feature = "use-rustls", feature = "websocket"))]
    #[cfg_attr(docsrs, doc(cfg(all(feature = "use-rustls", feature = "websocket"))))]
```

2024-06-18 08:02 UTC, de-sh approved these changes

2024-06-18 08:18 UTC, merged

2024-06-18 10:40 UTC, xiaocq2001 commented
Thanks.
WSS updates are here:
https://github.com/bytebeamio/rumqtt/pull/881